// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminalSession(arg1:string):Promise<void>;

export function CreateTerminalSession(arg1:string,arg2:string):Promise<void>;

export function GetAvailableTerminalTypes():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function IsTerminalSessionRunning(arg1:string):Promise<boolean>;

export function ListTerminalSessions():Promise<Array<string>>;

export function ResizeTerminalSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
