// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function CreateTerminalSession(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminalSession'](arg1, arg2);
}

export function GetAvailableTerminalTypes() {
  return window['go']['main']['App']['GetAvailableTerminalTypes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsTerminalSessionRunning(arg1) {
  return window['go']['main']['App']['IsTerminalSessionRunning'](arg1);
}

export function ListTerminalSessions() {
  return window['go']['main']['App']['ListTerminalSessions']();
}

export function ResizeTerminalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminalSession'](arg1, arg2, arg3);
}

export function WriteToTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteToTerminal'](arg1, arg2);
}
